#===
# ORF fasta file generated by transdecoder cannot be used to build blastdb 
# because ID include '|' character. This script clen the IDs.


#PREFIX = "RT2_"

PREFIX = ARGV[1]

File.open(ARGV[0]).each do |l|
	if /^>/.match(l)
		origid = /^>/.match(l).post_match.split[0]
		tp, orf = origid.split(/\|/)
		newid = "#{PREFIX}#{orf}"
		newdef = "#{newid} #{l.sub(/^>/, '')}"
		puts ">#{newdef}"
	else
		puts l
	end

end
